package com.chuangbu.rpc.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-08-27T16:53:08.080+08:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ServiceSoap")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ServiceSoap {

    @WebMethod(operationName = "DoTest", action = "http://tempuri.org/DoTest")
    @WebResult(name = "DoTestResult", targetNamespace = "http://tempuri.org/", partName = "DoTestResult")
    public java.lang.String doTest(
        @WebParam(partName = "InPutStr", name = "InPutStr")
        java.lang.String inPutStr
    );

    @WebMethod(operationName = "MzghService", action = "http://tempuri.org/MzghService")
    @WebResult(name = "MzghServiceResult", targetNamespace = "http://tempuri.org/", partName = "MzghServiceResult")
    public java.lang.String mzghService(
        @WebParam(partName = "request", name = "request")
        java.lang.String request
    );

    @WebMethod(operationName = "MzsfService", action = "http://tempuri.org/MzsfService")
    @WebResult(name = "MzsfServiceResult", targetNamespace = "http://tempuri.org/", partName = "MzsfServiceResult")
    public java.lang.String mzsfService(
        @WebParam(partName = "request", name = "request")
        java.lang.String request
    );
}
